Resources:
  DB:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName:
        Fn::Sub: ${self:service}-${self:provider.stage}
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        # Primary Key
        - AttributeName: PK
          # `<entity>#<entity-id>`
          AttributeType: S
        - AttributeName: SK
          # `<entity>#<entity-id>
          AttributeType: S
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
