Resources:
  # S3 Bucket for Frontend Hosting
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:service}-${self:provider.stage}-frontend
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true # was false?
    DeletionPolicy: Delete

  # S3 Bucket Policy to Grant CloudFront OAI Access
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: 'cloudfront.amazonaws.com'
            Action: 's3:GetObject'
            Resource:
              Fn::Sub:
                - ${s3BucketArn}/*
                - s3BucketArn:
                    Fn::GetAtt:
                      - FrontendBucket
                      - Arn
            Condition:
              StringEquals:
                AWS:SourceArn:
                  Fn::GetAtt:
                    - FrontendCloudFrontDistribution
                    - Arn

  # CloudFront Origin Access Identity (OAI)
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Access Identity for S3 Frontend Bucket'

  # CloudFront Distribution for the Frontend
  FrontendCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: allow-all # TODO use redirect-to-https?

        DefaultRootObject: index.html
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.DomainName

            S3OriginConfig: {}
          # - Id: ApiOrigin
          #   DomainName: ${self:custom.restApiDomainName}
          #   CustomOriginConfig:
          #     HTTPPort: 80
          #     HTTPSPort: 443
          #     OriginProtocolPolicy: https-only
        PriceClass: PriceClass_100

        # Custom error responses to handle SPA routing
        # CacheBehaviors:
        #   - PathPattern: '/api/*'
        #     TargetOriginId: ApiOrigin
        #     ViewerProtocolPolicy: https-only
        #     AllowedMethods:
        #       - GET
        #       - HEAD
        #       - OPTIONS
        #       - PUT
        #       - POST
        #       - PATCH
        #       - DELETE
        #     CachedMethods:
        #       - GET
        #       - HEAD
        CustomErrorResponses:
          - ErrorCode: 403
            ResponsePagePath: /index.html
            ResponseCode: 200
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponsePagePath: /index.html
            ResponseCode: 200
            ErrorCachingMinTTL: 0
