Resources:
  # S3 Bucket for Sector Images
  SectorImagesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: ${self:service}-${self:provider.stage}-sector-images
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
            AllowedHeaders:
              - '*'
            MaxAge: 3000
      LifecycleConfiguration:
        Rules:
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7

  # S3 Bucket Policy to Grant CloudFront OAC Access
  SectorImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SectorImagesBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontOAC
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource:
              Fn::Sub:
                - ${s3BucketArn}/*
                - s3BucketArn:
                    Fn::GetAtt:
                      - SectorImagesBucket
                      - Arn
            Condition:
              StringEquals:
                AWS:SourceArn:
                  Fn::Sub:
                    - arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistributionId}
                    - CloudFrontDistributionId:
                        Ref: SectorImagesCloudFrontDistribution

  # CloudFront Origin Access Control for Sector Images
  SectorImagesOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: ${self:service}-${self:provider.stage}-sector-images-OAC
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution for Sector Images
  SectorImagesCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          TargetOriginId: SectorImagesS3Origin
          ViewerProtocolPolicy: redirect-to-https
          # CachingOptimized - long TTL for images
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
        Origins:
          - Id: SectorImagesS3Origin
            DomainName:
              Fn::GetAtt:
                - SectorImagesBucket
                - RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId:
              Fn::GetAtt:
                - SectorImagesOriginAccessControl
                - Id
        Comment: CDN for sector images
        PriceClass: PriceClass_100
