services:
  database:
    container_name: database
    image: 'mongo:latest'
    ports:
      - '3200:27017'
    environment:
      - MONGO_INITDB_DATABASE=fit-log
    volumes:
      - mongodb-data:/data/db
      - mongodb-configdb:/data/configdb

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    ports:
      - '3380:8080'
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

  opensearch-local:
    container_name: opensearch-local
    image: opensearchproject/opensearch:latest
    ports:
      - '3400:9200' # REST API
      - '3401:9600' # Performance Analyzer
    environment:
      - discovery.type=single-node
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - DISABLE_SECURITY_PLUGIN=true # Disable security for local development
      - DISABLE_INSTALL_DEMO_CONFIG=true
    volumes:
      - opensearch-data:/usr/share/opensearch/data

volumes:
  mongodb-data:
    external: false
  mongodb-configdb:
    external: false
  s3-data:
    external: false
  keycloak-data:
    external: false
  opensearch-data:
    external: false
