#!/bin/bash
# Script to help complete the refactoring of all API handlers
# This provides the pattern - you can apply it file by file

echo "Remaining files to refactor:"
echo "1. workouts-get.ts - query params, requires auth"
echo "2. sessions-get.ts - query params, NO auth"
echo "3. sessions-put.ts - body, requires auth"
echo "4. users-post.ts - body, NO auth"
echo "5. users-authorize.ts - body, NO auth"
echo "6. locations-get.ts - query params, requires auth"
echo "7. locations-get-by-id.ts - path params {id}, requires auth"
echo "8. locations-put.ts - body, requires auth"
echo "9. locations-delete.ts - path params {id}, requires auth"
echo "10. sectors-get.ts - query params, requires auth"
echo "11. sectors-put.ts - body, requires auth"
echo "12. sectors-delete.ts - path params {id}, requires auth"
echo "13. sectors-upload-url.ts - body, requires auth"
echo "14. climbs-get.ts - query params, requires auth"
echo "15. climbs-get-by-id.ts - path params {id}, requires auth"
echo "16. climbs-put.ts - body, requires auth"
echo "17. favorite-workouts-put.ts - body, requires auth"
echo "18. favorite-workouts-delete.ts - path params {id}, requires auth"

echo ""
echo "Pattern for path params {id}:"
echo "type XxxParams = { id: string };"
echo "const handler = toApiResponse<XxxParams>(async (request) => {"
echo "  const { id } = request.params;"
echo ""
echo "Pattern for query params:"
echo "import { XxxGetParams } from '@shared/models/xxx';"
echo "const handler = toApiResponse<any, XxxGetParams>(async (request) => {"
echo "  const params = request.query;"
echo ""
echo "Pattern for body:"
echo "import { XxxRequest } from '@shared/models/xxx';"
echo "const handler = toApiResponse<any, any, XxxRequest>(async (request) => {"
echo "  const data = request.body;"
echo ""
echo "For auth, replace:"
echo "  assert(authorizerContext, ...)"
echo "with:"
echo "  assert(request.user, ...)"
echo "and:"
echo "  const { userId } = authorizerContext;"
echo "with:"
echo "  const { userId } = request.user;"
